---
- name: Update Debian packages
  hosts: "{{ target | default('all') }}"
  gather_facts: true
  become: true
  vars:
    apt_upgrade: dist
    apt_autoremove: true
    apt_autoclean: true
    reboot_if_required: false
  tasks:
    - name: Apt update
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Apt upgrade
      ansible.builtin.apt:
        upgrade: "{{ apt_upgrade }}"
      register: apt_result

    - name: Autoremove
      ansible.builtin.apt:
        autoremove: true
      when: apt_autoremove | bool

    - name: Autoclean
      ansible.builtin.apt:
        autoclean: true
      when: apt_autoclean | bool

    - name: Check reboot required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot if required
      ansible.builtin.reboot:
      when:
        - reboot_if_required | bool
        - reboot_required.stat.exists
